/**
 * NI ELVIS III Control Module Target Header File
 *
 * Definitions for NI ELVIS III Control Module
 * Copyright (c) 2017,
 * National Instruments Corporation.
 * All rights reserved.
 */

#ifndef __NiELVISIIIv10_Typedefs_h_
#define __NiELVISIIIv10_Typedefs_h_

/* Guard against direct include */
#ifndef NiELVISIIIv10_h_
#    error "Include NiELVISIIIv10.h instead of NiELVISIIIv10_Typedefs.h"
#endif


/**
 * Include NiFpga header files
 */
#include "NiFpga.h"
#include "NiFpga_ELVISIIIv10FPGA.h"


/**
 * Set the Bitfile and the Signtature
 */
#define NiELVISIIIv10_Bitfile	NiFpga_ELVISIIIv10FPGA_Bitfile
#define NiELVISIIIv10_Signature  NiFpga_ELVISIIIv10FPGA_Signature


/*
 * Define the IRQ number range
 */
#if !defined(IRQNO_MAX)
#define IRQNO_MAX  8
#endif

#if !defined(IRQNO_MIN)
#define IRQNO_MIN  1
#endif


/**
 * Redefinition of the NiFpga Bool Indicator enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadBool and NiFpga_WriteBool functions should be used to access these
 * items.
 */
typedef enum
{
    AIADMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_AIADMA_IDL,
    AIAVALRDY = NiFpga_ELVISIIIv10FPGA_IndicatorBool_AIAVALRDY,
    AIBDMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_AIBDMA_IDL,
    AIBVALRDY = NiFpga_ELVISIIIv10FPGA_IndicatorBool_AIBVALRDY,
    AOADMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_AOADMA_IDL,
    AOBDMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_AOBDMA_IDL,
    AOSYSSTAT = NiFpga_ELVISIIIv10FPGA_IndicatorBool_AOSYSSTAT,
    CONSOLEENA = NiFpga_ELVISIIIv10FPGA_IndicatorBool_CONSOLEENA,
    DIADMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_DIADMA_IDL,
    DIBDMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_DIBDMA_IDL,
    DOADMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_DOADMA_IDL,
    DOBDMA_IDL = NiFpga_ELVISIIIv10FPGA_IndicatorBool_DOBDMA_IDL,
    UARTASTAT = NiFpga_ELVISIIIv10FPGA_IndicatorBool_UARTASTAT,
    UARTBSTAT = NiFpga_ELVISIIIv10FPGA_IndicatorBool_UARTBSTAT,
} ELVISIIIFPGA_IndicatorBool;


/**
 * Redefinition of the NiFpga U8 Indicator enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU8 and NiFpga_WriteU8 functions should be used to access these
 * items.
 */
typedef enum
{
    DIBTN = NiFpga_ELVISIIIv10FPGA_IndicatorU8_DIBTN,
    ENCA_0STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_0STAT,
    ENCA_1STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_1STAT,
    ENCA_2STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_2STAT,
    ENCA_3STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_3STAT,
    ENCA_4STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_4STAT,
    ENCA_5STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_5STAT,
    ENCA_6STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_6STAT,
    ENCA_7STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_7STAT,
    ENCA_8STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_8STAT,
    ENCA_9STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCA_9STAT,
    ENCB_0STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_0STAT,
    ENCB_1STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_1STAT,
    ENCB_2STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_2STAT,
    ENCB_3STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_3STAT,
    ENCB_4STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_4STAT,
    ENCB_5STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_5STAT,
    ENCB_6STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_6STAT,
    ENCB_7STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_7STAT,
    ENCB_8STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_8STAT,
    ENCB_9STAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_ENCB_9STAT,
    I2CADATI = NiFpga_ELVISIIIv10FPGA_IndicatorU8_I2CADATI,
    I2CASTAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_I2CASTAT,
    I2CBDATI = NiFpga_ELVISIIIv10FPGA_IndicatorU8_I2CBDATI,
    I2CBSTAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_I2CBSTAT,
    SPIASTAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_SPIASTAT,
    SPIBSTAT = NiFpga_ELVISIIIv10FPGA_IndicatorU8_SPIBSTAT,
} ELVISIIIFPGA_IndicatorU8;


/**
 * Redefinition of the NiFpga U16 Indicator enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU16 and NiFpga_WriteU16 functions should be used to access these
 * items.
 */
typedef enum
{
    PWMA_0CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_0CNTR,
    PWMA_10CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_10CNTR,
    PWMA_11CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_11CNTR,
    PWMA_12CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_12CNTR,
    PWMA_13CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_13CNTR,
    PWMA_14CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_14CNTR,
    PWMA_15CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_15CNTR,
    PWMA_16CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_16CNTR,
    PWMA_17CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_17CNTR,
    PWMA_18CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_18CNTR,
    PWMA_19CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_19CNTR,
    PWMA_1CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_1CNTR,
    PWMA_2CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_2CNTR,
    PWMA_3CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_3CNTR,
    PWMA_4CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_4CNTR,
    PWMA_5CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_5CNTR,
    PWMA_6CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_6CNTR,
    PWMA_7CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_7CNTR,
    PWMA_8CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_8CNTR,
    PWMA_9CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMA_9CNTR,
    PWMB_0CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_0CNTR,
    PWMB_10CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_10CNTR,
    PWMB_11CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_11CNTR,
    PWMB_12CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_12CNTR,
    PWMB_13CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_13CNTR,
    PWMB_14CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_14CNTR,
    PWMB_15CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_15CNTR,
    PWMB_16CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_16CNTR,
    PWMB_17CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_17CNTR,
    PWMB_18CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_18CNTR,
    PWMB_19CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_19CNTR,
    PWMB_1CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_1CNTR,
    PWMB_2CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_2CNTR,
    PWMB_3CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_3CNTR,
    PWMB_4CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_4CNTR,
    PWMB_5CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_5CNTR,
    PWMB_6CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_6CNTR,
    PWMB_7CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_7CNTR,
    PWMB_8CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_8CNTR,
    PWMB_9CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU16_PWMB_9CNTR,
    SPIADATI = NiFpga_ELVISIIIv10FPGA_IndicatorU16_SPIADATI,
    SPIBDATI = NiFpga_ELVISIIIv10FPGA_IndicatorU16_SPIBDATI,
} ELVISIIIFPGA_IndicatorU16;


/**
 * Redefinition of the NiFpga U32 Indicator enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU32 and NiFpga_WriteU32 functions should be used to access these
 * items.
 */
typedef enum
{
    ENCA_0CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_0CNTR,
    ENCA_1CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_1CNTR,
    ENCA_2CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_2CNTR,
    ENCA_3CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_3CNTR,
    ENCA_4CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_4CNTR,
    ENCA_5CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_5CNTR,
    ENCA_6CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_6CNTR,
    ENCA_7CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_7CNTR,
    ENCA_8CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_8CNTR,
    ENCA_9CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCA_9CNTR,
    ENCB_0CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_0CNTR,
    ENCB_1CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_1CNTR,
    ENCB_2CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_2CNTR,
    ENCB_3CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_3CNTR,
    ENCB_4CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_4CNTR,
    ENCB_5CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_5CNTR,
    ENCB_6CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_6CNTR,
    ENCB_7CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_7CNTR,
    ENCB_8CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_8CNTR,
    ENCB_9CNTR = NiFpga_ELVISIIIv10FPGA_IndicatorU32_ENCB_9CNTR,
    IRQTIMERREAD = NiFpga_ELVISIIIv10FPGA_IndicatorU32_IRQTIMERREAD,
} ELVISIIIFPGA_IndicatorU32;


/**
 * Redefinition of the NiFpga Bool Control enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadBool and NiFpga_WriteBool functions should be used to access these
 * items.
 */
typedef enum
{
    AIADMA_ENA = NiFpga_ELVISIIIv10FPGA_ControlBool_AIADMA_ENA,
    AIBDMA_ENA = NiFpga_ELVISIIIv10FPGA_ControlBool_AIBDMA_ENA,
    AOSYSGO = NiFpga_ELVISIIIv10FPGA_ControlBool_AOSYSGO,
    DIADMA_ENA = NiFpga_ELVISIIIv10FPGA_ControlBool_DIADMA_ENA,
    DIBDMA_ENA = NiFpga_ELVISIIIv10FPGA_ControlBool_DIBDMA_ENA,
    I2CAGO = NiFpga_ELVISIIIv10FPGA_ControlBool_I2CAGO,
    I2CBGO = NiFpga_ELVISIIIv10FPGA_ControlBool_I2CBGO,
    IRQDI_BTNENA = NiFpga_ELVISIIIv10FPGA_ControlBool_IRQDI_BTNENA,
    IRQDI_BTNFALL = NiFpga_ELVISIIIv10FPGA_ControlBool_IRQDI_BTNFALL,
    IRQDI_BTNRISE = NiFpga_ELVISIIIv10FPGA_ControlBool_IRQDI_BTNRISE,
    IRQTIMERSETTIME = NiFpga_ELVISIIIv10FPGA_ControlBool_IRQTIMERSETTIME,
    SPIAGO = NiFpga_ELVISIIIv10FPGA_ControlBool_SPIAGO,
    SPIBGO = NiFpga_ELVISIIIv10FPGA_ControlBool_SPIBGO,
    UARTAENA = NiFpga_ELVISIIIv10FPGA_ControlBool_UARTAENA,
    UARTBENA = NiFpga_ELVISIIIv10FPGA_ControlBool_UARTBENA,
} ELVISIIIFPGA_ControlBool;


/**
 * Redefinition of the NiFpga U8 Control enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU8 and NiFpga_WriteU8 functions should be used to access these
 * items.
 */
typedef enum
{
    AIACNT = NiFpga_ELVISIIIv10FPGA_ControlU8_AIACNT,
    AIBCNT = NiFpga_ELVISIIIv10FPGA_ControlU8_AIBCNT,
    DOLED30 = NiFpga_ELVISIIIv10FPGA_ControlU8_DOLED30,
    ENCA_0CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_0CNFG,
    ENCA_1CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_1CNFG,
    ENCA_2CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_2CNFG,
    ENCA_3CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_3CNFG,
    ENCA_4CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_4CNFG,
    ENCA_5CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_5CNFG,
    ENCA_6CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_6CNFG,
    ENCA_7CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_7CNFG,
    ENCA_8CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_8CNFG,
    ENCA_9CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCA_9CNFG,
    ENCB_0CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_0CNFG,
    ENCB_1CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_1CNFG,
    ENCB_2CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_2CNFG,
    ENCB_3CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_3CNFG,
    ENCB_4CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_4CNFG,
    ENCB_5CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_5CNFG,
    ENCB_6CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_6CNFG,
    ENCB_7CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_7CNFG,
    ENCB_8CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_8CNFG,
    ENCB_9CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_ENCB_9CNFG,
    I2CAADDR = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CAADDR,
    I2CACNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CACNFG,
    I2CACNTL = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CACNTL,
    I2CACNTR = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CACNTR,
    I2CADATO = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CADATO,
    I2CBADDR = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CBADDR,
    I2CBCNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CBCNFG,
    I2CBCNTL = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CBCNTL,
    I2CBCNTR = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CBCNTR,
    I2CBDATO = NiFpga_ELVISIIIv10FPGA_ControlU8_I2CBDATO,
    IRQAI_ACNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQAI_ACNFG,
    IRQAI_A_0NO = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQAI_A_0NO,
    IRQAI_A_1NO = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQAI_A_1NO,
    IRQDIO_A_0NO = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDIO_A_0NO,
    IRQDIO_A_1NO = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDIO_A_1NO,
    IRQDIO_A_2NO = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDIO_A_2NO,
    IRQDIO_A_3NO = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDIO_A_3NO,
    IRQDIO_A_70ENA = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDIO_A_70ENA,
    IRQDIO_A_70FALL = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDIO_A_70FALL,
    IRQDIO_A_70RISE = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDIO_A_70RISE,
    IRQDI_BTNNO = NiFpga_ELVISIIIv10FPGA_ControlU8_IRQDI_BTNNO,
    PWMA_0CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_0CNFG,
    PWMA_0CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_0CS,
    PWMA_10CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_10CNFG,
    PWMA_10CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_10CS,
    PWMA_11CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_11CNFG,
    PWMA_11CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_11CS,
    PWMA_12CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_12CNFG,
    PWMA_12CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_12CS,
    PWMA_13CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_13CNFG,
    PWMA_13CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_13CS,
    PWMA_14CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_14CNFG,
    PWMA_14CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_14CS,
    PWMA_15CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_15CNFG,
    PWMA_15CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_15CS,
    PWMA_16CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_16CNFG,
    PWMA_16CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_16CS,
    PWMA_17CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_17CNFG,
    PWMA_17CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_17CS,
    PWMA_18CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_18CNFG,
    PWMA_18CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_18CS,
    PWMA_19CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_19CNFG,
    PWMA_19CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_19CS,
    PWMA_1CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_1CNFG,
    PWMA_1CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_1CS,
    PWMA_2CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_2CNFG,
    PWMA_2CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_2CS,
    PWMA_3CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_3CNFG,
    PWMA_3CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_3CS,
    PWMA_4CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_4CNFG,
    PWMA_4CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_4CS,
    PWMA_5CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_5CNFG,
    PWMA_5CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_5CS,
    PWMA_6CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_6CNFG,
    PWMA_6CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_6CS,
    PWMA_7CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_7CNFG,
    PWMA_7CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_7CS,
    PWMA_8CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_8CNFG,
    PWMA_8CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_8CS,
    PWMA_9CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_9CNFG,
    PWMA_9CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMA_9CS,
    PWMB_0CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_0CNFG,
    PWMB_0CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_0CS,
    PWMB_10CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_10CNFG,
    PWMB_10CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_10CS,
    PWMB_11CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_11CNFG,
    PWMB_11CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_11CS,
    PWMB_12CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_12CNFG,
    PWMB_12CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_12CS,
    PWMB_13CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_13CNFG,
    PWMB_13CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_13CS,
    PWMB_14CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_14CNFG,
    PWMB_14CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_14CS,
    PWMB_15CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_15CNFG,
    PWMB_15CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_15CS,
    PWMB_16CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_16CNFG,
    PWMB_16CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_16CS,
    PWMB_17CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_17CNFG,
    PWMB_17CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_17CS,
    PWMB_18CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_18CNFG,
    PWMB_18CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_18CS,
    PWMB_19CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_19CNFG,
    PWMB_19CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_19CS,
    PWMB_1CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_1CNFG,
    PWMB_1CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_1CS,
    PWMB_2CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_2CNFG,
    PWMB_2CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_2CS,
    PWMB_3CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_3CNFG,
    PWMB_3CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_3CS,
    PWMB_4CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_4CNFG,
    PWMB_4CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_4CS,
    PWMB_5CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_5CNFG,
    PWMB_5CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_5CS,
    PWMB_6CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_6CNFG,
    PWMB_6CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_6CS,
    PWMB_7CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_7CNFG,
    PWMB_7CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_7CS,
    PWMB_8CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_8CNFG,
    PWMB_8CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_8CS,
    PWMB_9CNFG = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_9CNFG,
    PWMB_9CS = NiFpga_ELVISIIIv10FPGA_ControlU8_PWMB_9CS,
} ELVISIIIFPGA_ControlU8;


/**
 * Redefinition of the NiFpga U16 Control enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU16 and NiFpga_WriteU16 functions should be used to access these
 * items.
 */
typedef enum
{
    DIADMA_CNTR = NiFpga_ELVISIIIv10FPGA_ControlU16_DIADMA_CNTR,
    DIBDMA_CNTR = NiFpga_ELVISIIIv10FPGA_ControlU16_DIBDMA_CNTR,
    DOADMA_CNTR = NiFpga_ELVISIIIv10FPGA_ControlU16_DOADMA_CNTR,
    DOBDMA_CNTR = NiFpga_ELVISIIIv10FPGA_ControlU16_DOBDMA_CNTR,
    PWMA_0CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_0CMP,
    PWMA_0MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_0MAX,
    PWMA_10CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_10CMP,
    PWMA_10MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_10MAX,
    PWMA_11CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_11CMP,
    PWMA_11MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_11MAX,
    PWMA_12CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_12CMP,
    PWMA_12MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_12MAX,
    PWMA_13CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_13CMP,
    PWMA_13MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_13MAX,
    PWMA_14CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_14CMP,
    PWMA_14MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_14MAX,
    PWMA_15CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_15CMP,
    PWMA_15MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_15MAX,
    PWMA_16CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_16CMP,
    PWMA_16MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_16MAX,
    PWMA_17CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_17CMP,
    PWMA_17MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_17MAX,
    PWMA_18CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_18CMP,
    PWMA_18MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_18MAX,
    PWMA_19CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_19CMP,
    PWMA_19MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_19MAX,
    PWMA_1CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_1CMP,
    PWMA_1MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_1MAX,
    PWMA_2CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_2CMP,
    PWMA_2MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_2MAX,
    PWMA_3CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_3CMP,
    PWMA_3MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_3MAX,
    PWMA_4CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_4CMP,
    PWMA_4MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_4MAX,
    PWMA_5CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_5CMP,
    PWMA_5MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_5MAX,
    PWMA_6CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_6CMP,
    PWMA_6MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_6MAX,
    PWMA_7CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_7CMP,
    PWMA_7MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_7MAX,
    PWMA_8CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_8CMP,
    PWMA_8MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_8MAX,
    PWMA_9CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_9CMP,
    PWMA_9MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMA_9MAX,
    PWMB_0CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_0CMP,
    PWMB_0MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_0MAX,
    PWMB_10CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_10CMP,
    PWMB_10MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_10MAX,
    PWMB_11CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_11CMP,
    PWMB_11MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_11MAX,
    PWMB_12CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_12CMP,
    PWMB_12MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_12MAX,
    PWMB_13CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_13CMP,
    PWMB_13MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_13MAX,
    PWMB_14CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_14CMP,
    PWMB_14MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_14MAX,
    PWMB_15CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_15CMP,
    PWMB_15MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_15MAX,
    PWMB_16CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_16CMP,
    PWMB_16MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_16MAX,
    PWMB_17CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_17CMP,
    PWMB_17MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_17MAX,
    PWMB_18CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_18CMP,
    PWMB_18MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_18MAX,
    PWMB_19CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_19CMP,
    PWMB_19MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_19MAX,
    PWMB_1CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_1CMP,
    PWMB_1MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_1MAX,
    PWMB_2CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_2CMP,
    PWMB_2MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_2MAX,
    PWMB_3CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_3CMP,
    PWMB_3MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_3MAX,
    PWMB_4CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_4CMP,
    PWMB_4MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_4MAX,
    PWMB_5CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_5CMP,
    PWMB_5MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_5MAX,
    PWMB_6CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_6CMP,
    PWMB_6MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_6MAX,
    PWMB_7CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_7CMP,
    PWMB_7MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_7MAX,
    PWMB_8CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_8CMP,
    PWMB_8MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_8MAX,
    PWMB_9CMP = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_9CMP,
    PWMB_9MAX = NiFpga_ELVISIIIv10FPGA_ControlU16_PWMB_9MAX,
    SPIACNFG = NiFpga_ELVISIIIv10FPGA_ControlU16_SPIACNFG,
    SPIACNT = NiFpga_ELVISIIIv10FPGA_ControlU16_SPIACNT,
    SPIADATO = NiFpga_ELVISIIIv10FPGA_ControlU16_SPIADATO,
    SPIBCNFG = NiFpga_ELVISIIIv10FPGA_ControlU16_SPIBCNFG,
    SPIBCNT = NiFpga_ELVISIIIv10FPGA_ControlU16_SPIBCNT,
    SPIBDATO = NiFpga_ELVISIIIv10FPGA_ControlU16_SPIBDATO,
} ELVISIIIFPGA_ControlU16;


/**
 * Redefinition of the NiFpga U32 Control enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU32 and NiFpga_WriteU32 functions should be used to access these
 * items.
 */
typedef enum
{
    AIACNTR = NiFpga_ELVISIIIv10FPGA_ControlU32_AIACNTR,
    AIBCNTR = NiFpga_ELVISIIIv10FPGA_ControlU32_AIBCNTR,
    AOADMA_CNTR = NiFpga_ELVISIIIv10FPGA_ControlU32_AOADMA_CNTR,
    AOBDMA_CNTR = NiFpga_ELVISIIIv10FPGA_ControlU32_AOBDMA_CNTR,
    IRQDIO_A_0CNT = NiFpga_ELVISIIIv10FPGA_ControlU32_IRQDIO_A_0CNT,
    IRQDIO_A_1CNT = NiFpga_ELVISIIIv10FPGA_ControlU32_IRQDIO_A_1CNT,
    IRQDIO_A_2CNT = NiFpga_ELVISIIIv10FPGA_ControlU32_IRQDIO_A_2CNT,
    IRQDIO_A_3CNT = NiFpga_ELVISIIIv10FPGA_ControlU32_IRQDIO_A_3CNT,
    IRQDI_BTNCNT = NiFpga_ELVISIIIv10FPGA_ControlU32_IRQDI_BTNCNT,
    IRQTIMERWRITE = NiFpga_ELVISIIIv10FPGA_ControlU32_IRQTIMERWRITE,
} ELVISIIIFPGA_ControlU32;


/**
 * Redefinition of the NiFpga U64 Control enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU64 and NiFpga_WriteU64 functions should be used to access these
 * items.
 */
typedef enum
{
    SYSSELECTA = NiFpga_ELVISIIIv10FPGA_ControlU64_SYSSELECTA,
    SYSSELECTB = NiFpga_ELVISIIIv10FPGA_ControlU64_SYSSELECTB,
} ELVISIIIFPGA_ControlU64;


/**
 * Redefinition of the NiFpga U8 ControlArray enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU8 and NiFpga_WriteU8 functions should be used to access these
 * items.
 */
typedef enum
{
    AIACNFG = NiFpga_ELVISIIIv10FPGA_ControlArrayU8_AIACNFG,
    AIBCNFG = NiFpga_ELVISIIIv10FPGA_ControlArrayU8_AIBCNFG,
} ELVISIIIFPGA_ControlArrayU8;


/**
 * Redefinition of the NiFpga U8 ControlArraySize enum.
 * This is provided as a convenience to shorten the default enum names. The
 * NiFpga_ReadU8 and NiFpga_WriteU8 functions should be used to access these
 * items.
 */
typedef enum
{
    Size_AIACNFG = NiFpga_ELVISIIIv10FPGA_ControlArrayU8Size_AIACNFG,
    Size_AIBCNFG = NiFpga_ELVISIIIv10FPGA_ControlArrayU8Size_AIBCNFG,
} ELVISIIIFPGA_ControlArrayU8Size;


#endif /* NiELVISIIIv10_Typedefs_h_ */
